# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BT-Basilica-Assist.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 773)
        MainWindow.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setMaximumSize(QtCore.QSize(800, 200))
        self.label.setStyleSheet("image: url(:/valve/images/BasilicaCurve.png);\n"
"\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ManValBox = QtWidgets.QGroupBox(self.frame)
        self.ManValBox.setMinimumSize(QtCore.QSize(0, 0))
        self.ManValBox.setObjectName("ManValBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ManValBox)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ValFrame = QtWidgets.QFrame(self.ManValBox)
        self.ValFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.ValFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ValFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ValFrame.setObjectName("ValFrame")


        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ValFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")


        self.gbXYZ = QtWidgets.QGroupBox(self.ValFrame)
        self.gbXYZ.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.gbXYZ.setPalette(palette)
        self.gbXYZ.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.gbXYZ.setObjectName("gbXYZ")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbXYZ)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.gbXYZ)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.xlabel = QtWidgets.QLabel(self.frame_4)
        self.xlabel.setObjectName("xlabel")
        self.horizontalLayout_8.addWidget(self.xlabel)
        self.vxLCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxLCC.sizePolicy().hasHeightForWidth())
        self.vxLCC.setSizePolicy(sizePolicy)
        self.vxLCC.setMinimumSize(QtCore.QSize(0, 0))
        self.vxLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxLCC.setObjectName("vxLCC")
        self.horizontalLayout_8.addWidget(self.vxLCC)
        self.vyLCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyLCC.sizePolicy().hasHeightForWidth())
        self.vyLCC.setSizePolicy(sizePolicy)
        self.vyLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyLCC.setObjectName("vyLCC")
        self.horizontalLayout_8.addWidget(self.vyLCC)
        self.vzLCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzLCC.sizePolicy().hasHeightForWidth())
        self.vzLCC.setSizePolicy(sizePolicy)
        self.vzLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzLCC.setObjectName("vzLCC")
        self.horizontalLayout_8.addWidget(self.vzLCC)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.gbXYZ)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ylabel = QtWidgets.QLabel(self.frame_5)
        self.ylabel.setMinimumSize(QtCore.QSize(0, 50))
        self.ylabel.setObjectName("ylabel")
        self.horizontalLayout_9.addWidget(self.ylabel)
        self.vxRCC = QtWidgets.QTextEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxRCC.sizePolicy().hasHeightForWidth())
        self.vxRCC.setSizePolicy(sizePolicy)
        self.vxRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxRCC.setObjectName("vxRCC")
        self.horizontalLayout_9.addWidget(self.vxRCC)
        self.vyRCC = QtWidgets.QTextEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyRCC.sizePolicy().hasHeightForWidth())
        self.vyRCC.setSizePolicy(sizePolicy)
        self.vyRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyRCC.setObjectName("vyRCC")
        self.horizontalLayout_9.addWidget(self.vyRCC)
        self.vzRCC = QtWidgets.QTextEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzRCC.sizePolicy().hasHeightForWidth())
        self.vzRCC.setSizePolicy(sizePolicy)
        self.vzRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzRCC.setObjectName("vzRCC")
        self.horizontalLayout_9.addWidget(self.vzRCC)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.gbXYZ)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.zlabel = QtWidgets.QLabel(self.frame_6)
        self.zlabel.setMinimumSize(QtCore.QSize(0, 50))
        self.zlabel.setObjectName("zlabel")
        self.horizontalLayout_10.addWidget(self.zlabel)
        self.vxNCC = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxNCC.sizePolicy().hasHeightForWidth())
        self.vxNCC.setSizePolicy(sizePolicy)
        self.vxNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxNCC.setObjectName("vxNCC")
        self.horizontalLayout_10.addWidget(self.vxNCC)
        self.vyNCC = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyNCC.sizePolicy().hasHeightForWidth())
        self.vyNCC.setSizePolicy(sizePolicy)
        self.vyNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyNCC.setObjectName("vyNCC")
        self.horizontalLayout_10.addWidget(self.vyNCC)
        self.vzNCC = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzNCC.sizePolicy().hasHeightForWidth())
        self.vzNCC.setSizePolicy(sizePolicy)
        self.vzNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzNCC.setObjectName("vzNCC")
        self.horizontalLayout_10.addWidget(self.vzNCC)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.fbtnXYZ = QtWidgets.QFrame(self.gbXYZ)
        self.fbtnXYZ.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.fbtnXYZ.setPalette(palette)
        self.fbtnXYZ.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fbtnXYZ.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fbtnXYZ.setObjectName("fbtnXYZ")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fbtnXYZ)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnXYZ = QtWidgets.QPushButton(self.fbtnXYZ)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXYZ.sizePolicy().hasHeightForWidth())
        self.btnXYZ.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/valve/D:/NBME/aortic-valve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnXYZ.setIcon(icon)
        self.btnXYZ.setObjectName("btnXYZ")
        self.horizontalLayout_3.addWidget(self.btnXYZ)
        self.btnHelpXYZ = QtWidgets.QPushButton(self.fbtnXYZ)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHelpXYZ.sizePolicy().hasHeightForWidth())
        self.btnHelpXYZ.setSizePolicy(sizePolicy)
        self.btnHelpXYZ.setObjectName("btnHelpXYZ")
        self.horizontalLayout_3.addWidget(self.btnHelpXYZ)
        self.verticalLayout_9.addWidget(self.fbtnXYZ)
        self.horizontalLayout_4.addWidget(self.gbXYZ)
        self.val1Box_3 = QtWidgets.QGroupBox(self.ValFrame)
        self.val1Box_3.setMinimumSize(QtCore.QSize(0, 50))
        self.val1Box_3.setObjectName("val1Box_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.val1Box_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lxRLV1_3 = QtWidgets.QLabel(self.val1Box_3)
        self.lxRLV1_3.setObjectName("lxRLV1_3")
        self.verticalLayout_8.addWidget(self.lxRLV1_3)
        self.xRL_LLC_Front_TextEdit = QtWidgets.QTextEdit(self.val1Box_3)
        self.xRL_LLC_Front_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xRL_LLC_Front_TextEdit.setObjectName("xRL_LLC_Front_TextEdit")
        self.verticalLayout_8.addWidget(self.xRL_LLC_Front_TextEdit)
        self.lxCCV1_3 = QtWidgets.QLabel(self.val1Box_3)
        self.lxCCV1_3.setObjectName("lxCCV1_3")
        self.verticalLayout_8.addWidget(self.lxCCV1_3)
        self.xCC_LLC_Front_TextEdit = QtWidgets.QTextEdit(self.val1Box_3)
        self.xCC_LLC_Front_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xCC_LLC_Front_TextEdit.setObjectName("xCC_LLC_Front_TextEdit")
        self.verticalLayout_8.addWidget(self.xCC_LLC_Front_TextEdit)
        self.horizontalLayout_4.addWidget(self.val1Box_3)
        self.val1Box_2 = QtWidgets.QGroupBox(self.ValFrame)
        self.val1Box_2.setMinimumSize(QtCore.QSize(0, 50))
        self.val1Box_2.setObjectName("val1Box_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.val1Box_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lxRLV1_2 = QtWidgets.QLabel(self.val1Box_2)
        self.lxRLV1_2.setObjectName("lxRLV1_2")
        self.verticalLayout_7.addWidget(self.lxRLV1_2)
        self.xRL_LLC_Side_TextEdit = QtWidgets.QTextEdit(self.val1Box_2)
        self.xRL_LLC_Side_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xRL_LLC_Side_TextEdit.setObjectName("xRL_LLC_Side_TextEdit")
        self.verticalLayout_7.addWidget(self.xRL_LLC_Side_TextEdit)
        self.lxCCV1_2 = QtWidgets.QLabel(self.val1Box_2)
        self.lxCCV1_2.setObjectName("lxCCV1_2")
        self.verticalLayout_7.addWidget(self.lxCCV1_2)
        self.xCC_LLC_Side_TextEdit = QtWidgets.QTextEdit(self.val1Box_2)
        self.xCC_LLC_Side_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xCC_LLC_Side_TextEdit.setObjectName("xCC_LLC_Side_TextEdit")
        self.verticalLayout_7.addWidget(self.xCC_LLC_Side_TextEdit)
        self.horizontalLayout_4.addWidget(self.val1Box_2)
        self.val1Box = QtWidgets.QGroupBox(self.ValFrame)
        self.val1Box.setMinimumSize(QtCore.QSize(0, 50))
        self.val1Box.setObjectName("val1Box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.val1Box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lxRLV1 = QtWidgets.QLabel(self.val1Box)
        self.lxRLV1.setObjectName("lxRLV1")
        self.verticalLayout_3.addWidget(self.lxRLV1)
        self.xRL_RCC_Front_TextEdit = QtWidgets.QTextEdit(self.val1Box)
        self.xRL_RCC_Front_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xRL_RCC_Front_TextEdit.setObjectName("xRL_RCC_Front_TextEdit")
        self.verticalLayout_3.addWidget(self.xRL_RCC_Front_TextEdit)
        self.lxCCV1 = QtWidgets.QLabel(self.val1Box)
        self.lxCCV1.setObjectName("lxCCV1")
        self.verticalLayout_3.addWidget(self.lxCCV1)
        self.xCC_RCC_Front_TextEdit = QtWidgets.QTextEdit(self.val1Box)
        self.xCC_RCC_Front_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xCC_RCC_Front_TextEdit.setObjectName("xCC_RCC_Front_TextEdit")
        self.verticalLayout_3.addWidget(self.xCC_RCC_Front_TextEdit)
        self.horizontalLayout_4.addWidget(self.val1Box)
        self.val2Box = QtWidgets.QGroupBox(self.ValFrame)
        self.val2Box.setMinimumSize(QtCore.QSize(0, 50))
        self.val2Box.setObjectName("val2Box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.val2Box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lxRLV2 = QtWidgets.QLabel(self.val2Box)
        self.lxRLV2.setObjectName("lxRLV2")
        self.verticalLayout_5.addWidget(self.lxRLV2)
        self.xRL_RCC_Side_TextEdit = QtWidgets.QTextEdit(self.val2Box)
        self.xRL_RCC_Side_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xRL_RCC_Side_TextEdit.setObjectName("xRL_RCC_Side_TextEdit")
        self.verticalLayout_5.addWidget(self.xRL_RCC_Side_TextEdit)
        self.lxRCC2 = QtWidgets.QLabel(self.val2Box)
        self.lxRCC2.setObjectName("lxRCC2")
        self.verticalLayout_5.addWidget(self.lxRCC2)
        self.xCC_RCC_Side_TextEdit = QtWidgets.QTextEdit(self.val2Box)
        self.xCC_RCC_Side_TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.xCC_RCC_Side_TextEdit.setObjectName("xCC_RCC_Side_TextEdit")
        self.verticalLayout_5.addWidget(self.xCC_RCC_Side_TextEdit)
        self.horizontalLayout_4.addWidget(self.val2Box)
        self.btnframe = QtWidgets.QFrame(self.ValFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnframe.sizePolicy().hasHeightForWidth())
        self.btnframe.setSizePolicy(sizePolicy)
        self.btnframe.setMinimumSize(QtCore.QSize(0, 0))
        self.btnframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnframe.setObjectName("btnframe")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.btnframe)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMakeCatheterSC = QtWidgets.QPushButton(self.btnframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMakeCatheterSC.sizePolicy().hasHeightForWidth())
        self.btnMakeCatheterSC.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/replacement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMakeCatheterSC.setIcon(icon1)
        self.btnMakeCatheterSC.setIconSize(QtCore.QSize(40, 40))
        self.btnMakeCatheterSC.setObjectName("btnMakeCatheterSC")
        self.verticalLayout.addWidget(self.btnMakeCatheterSC)
        self.btnHelpMan = QtWidgets.QPushButton(self.btnframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHelpMan.sizePolicy().hasHeightForWidth())
        self.btnHelpMan.setSizePolicy(sizePolicy)
        self.btnHelpMan.setIconSize(QtCore.QSize(40, 40))
        self.btnHelpMan.setObjectName("btnHelpMan")
        self.verticalLayout.addWidget(self.btnHelpMan)
        self.horizontalLayout_4.addWidget(self.btnframe)
        self.horizontalLayout_7.addWidget(self.ValFrame)
        self.autoBox = QtWidgets.QGroupBox(self.ManValBox)
        self.autoBox.setObjectName("autoBox")



        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.autoBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnGetBTV1 = QtWidgets.QPushButton(self.autoBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/D:/NBME/bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGetBTV1.setIcon(icon2)
        self.btnGetBTV1.setObjectName("btnGetBTV1")
        self.verticalLayout_4.addWidget(self.btnGetBTV1)
        self.btnGetBTV2 = QtWidgets.QPushButton(self.autoBox)
        self.btnGetBTV2.setIcon(icon2)
        self.btnGetBTV2.setObjectName("btnGetBTV2")
        self.verticalLayout_4.addWidget(self.btnGetBTV2)
        self.btnft = QtWidgets.QPushButton(self.autoBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnft.setPalette(palette)
        self.btnft.setIcon(icon2)
        self.btnft.setIconSize(QtCore.QSize(40, 40))
        self.btnft.setObjectName("btnft")
        self.verticalLayout_4.addWidget(self.btnft)
        self.btnHelpAuto = QtWidgets.QPushButton(self.autoBox)
        self.btnHelpAuto.setObjectName("btnHelpAuto")
        self.verticalLayout_4.addWidget(self.btnHelpAuto)
        self.horizontalLayout_7.addWidget(self.autoBox)
        self.horizontalLayout_2.addWidget(self.ManValBox)

        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnAVCurve = QtWidgets.QPushButton(self.groupBox)
        self.btnAVCurve.setIcon(icon)
        self.btnAVCurve.setIconSize(QtCore.QSize(40, 40))
        self.btnAVCurve.setObjectName("btnAVCurve")
        self.verticalLayout_6.addWidget(self.btnAVCurve)
        self.LoadAorta = QtWidgets.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/aorta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoadAorta.setIcon(icon3)
        self.LoadAorta.setIconSize(QtCore.QSize(40, 40))
        self.LoadAorta.setObjectName("LoadAorta")
        self.verticalLayout_6.addWidget(self.LoadAorta)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1329, 18))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ManValBox.setTitle(_translate("MainWindow", "Bioprosthetic S-Curve"))
        self.gbXYZ.setTitle(_translate("MainWindow", "Comissure Coordinates Values"))
        self.xlabel.setText(_translate("MainWindow", "LNC Coordinates"))
        self.vxLCC.setPlaceholderText(_translate("MainWindow", "X Value"))
        self.vyLCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzLCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.ylabel.setText(_translate("MainWindow", "RNC Coordinates"))
        self.vxRCC.setPlaceholderText(_translate("MainWindow", "X Value"))
        self.vyRCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzRCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.zlabel.setText(_translate("MainWindow", "LRC Coordinates"))
        self.vxNCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.vyNCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzNCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.btnXYZ.setText(_translate("MainWindow", "Calculate"))
        self.btnHelpXYZ.setText(_translate("MainWindow", "Help"))
        self.val1Box_3.setTitle(_translate("MainWindow", "Frontal View LCC"))
        self.lxRLV1_3.setText(_translate("MainWindow", "LAO/RAO"))
        self.xRL_LLC_Front_TextEdit.setPlaceholderText(_translate("MainWindow", "LAO in Postive, RAO in Negative"))
        self.lxCCV1_3.setText(_translate("MainWindow", "CRAN/CAUD"))
        self.xCC_LLC_Front_TextEdit.setPlaceholderText(_translate("MainWindow", "CRAN in Postive, CAUD in Negative"))
        self.val1Box_2.setTitle(_translate("MainWindow", "Side View LCC"))
        self.lxRLV1_2.setText(_translate("MainWindow", "LAO/RAO"))
        self.xRL_LLC_Side_TextEdit.setPlaceholderText(_translate("MainWindow", "LAO in Postive, RAO in Negative"))
        self.lxCCV1_2.setText(_translate("MainWindow", "CRAN/CAUD"))
        self.xCC_LLC_Side_TextEdit.setPlaceholderText(_translate("MainWindow", "CRAN in Postive, CAUD in Negative"))
        self.val1Box.setTitle(_translate("MainWindow", "Frontal View RCC"))
        self.lxRLV1.setText(_translate("MainWindow", "LAO/RAO"))
        self.xRL_RCC_Front_TextEdit.setPlaceholderText(_translate("MainWindow", "LAO in Postive, RAO in Negative"))
        self.lxCCV1.setText(_translate("MainWindow", "CRAN/CAUD"))
        self.xCC_RCC_Front_TextEdit.setPlaceholderText(_translate("MainWindow", "CRAN in Postive, CAUD in Negative"))
        self.val2Box.setTitle(_translate("MainWindow", "Side View RCC"))
        self.lxRLV2.setText(_translate("MainWindow", "LAO/RAO"))
        self.xRL_RCC_Side_TextEdit.setPlaceholderText(_translate("MainWindow", "LAO in Postive, RAO in Negative"))
        self.lxRCC2.setText(_translate("MainWindow", "CRAN/CAUD"))
        self.xCC_RCC_Side_TextEdit.setPlaceholderText(_translate("MainWindow", "CRAN in Postive, CAUD in Negative"))
        self.btnMakeCatheterSC.setText(_translate("MainWindow", "S-Curve Valve"))
        self.btnHelpMan.setText(_translate("MainWindow", "Help"))
        self.autoBox.setTitle(_translate("MainWindow", "Automatic Valve S-Curve"))
        self.btnGetBTV1.setText(_translate("MainWindow", "Get Frontal View"))
        self.btnGetBTV2.setText(_translate("MainWindow", "Get Side View"))
        self.btnft.setText(_translate("MainWindow", "FluoroTracker"))
        self.btnHelpAuto.setText(_translate("MainWindow", "Help"))
        self.groupBox.setTitle(_translate("MainWindow", "Aorta"))
        self.btnAVCurve.setText(_translate("MainWindow", "Get AV S Curve"))
        self.LoadAorta.setText(_translate("MainWindow", "Load Valve"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

import test_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

