from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.ticker import MultipleLocator, AutoMinorLocator
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

import NAVICath, DB



class Ui_MainWindow(object):
    def Get_Scurve_XYZ(self):

        Lx=int(self.vxLCC.toPlainText())
        Ly = int(self.vyLCC.toPlainText())
        Lz = int(self.vzLCC.toPlainText())

        Rx = int(self.vxRCC.toPlainText())
        Ry = int(self.vyRCC.toPlainText())
        Rz = int(self.vzRCC.toPlainText())

        Nx = int(self.vxNCC.toPlainText())
        Ny = int(self.vyNCC.toPlainText())
        Nz = int(self.vzNCC.toPlainText())

        cord = [Lx, Ly, Lz, Rx, Ry, Rz, Nx, Ny, Nz]
        cordinates = ",".join(map(str, cord))

        # save values to System
        values = (DB.patientsDB.myExam, "AV/MDCT/Coordinates", cordinates)
        DB.patientsDB.add_value(values)


        self.data = NAVICath.SCurve_XYZ(Lx,Ly,Lz,Rx,Ry,Rz,Nx,Ny,Nz)
        self.Scurve_XYZ = self.ax.plot(range(-90, 90), self.data, label="Coordinates", color="red")
        self.ax.legend(loc="upper left")
        self.canvas.draw()

    def Get_Scurve_enface(self):

        enRL = int(self.vRLEnface.toPlainText())
        enCC = int(self.vCCEnface.toPlainText())

        enface = [enRL,enCC]
        enface = ",".join(map(str, enface))

        # save values to System
        values = (DB.patientsDB.myExam, "AV/MDCT/Enface", enface)
        DB.patientsDB.add_value(values)


        self.data=NAVICath.make_s_curve_array(enRL,enCC)
        self.Scurve_enface = self.ax.plot(range(-90, 90), self.data, label="Enface", color="green")
        self.ax.legend(loc="upper left")
        self.canvas.draw()

    def Get_SCruve_Plane(self):
        xRL1=int(self.vRLP1.toPlainText())
        xRL2=int(self.vRLP2.toPlainText())
        xCC1=int(self.vCCP1.toPlainText())
        xCC2=int(self.vCCP2.toPlainText())

        planes = [xCC1,xRL1,xCC2,xRL2]
        planes = ",".join(map(str, planes))

        # save values to System
        values = (DB.patientsDB.myExam, "AV/MDCT/Planes", planes)
        DB.patientsDB.add_value(values)

        self.data=NAVICath.get_s_curve_device(xCC1,xRL1,xCC2,xRL2)
        self.SCruve_Plane = self.ax.plot(range(-90, 90), self.data, label="Plannar", color="blue")
        self.canvas.draw()

    def goBack(self):
        MainWindow.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 821)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/aortic-valve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MDCTTitle = QtWidgets.QLabel(self.frame_3)
        self.MDCTTitle.setMinimumSize(QtCore.QSize(500, 100))
        self.MDCTTitle.setMaximumSize(QtCore.QSize(800, 200))
        self.MDCTTitle.setStyleSheet("image: url(./images/MDCT-S-Curve.png);")
        self.MDCTTitle.setText("")
        self.MDCTTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.MDCTTitle.setObjectName("MDCTTitle")
        self.horizontalLayout.addWidget(self.MDCTTitle)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.graphframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphframe.sizePolicy().hasHeightForWidth())
        self.graphframe.setSizePolicy(sizePolicy)
        self.graphframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphframe.setObjectName("graphframe")

        # ------------------------------copy from here to add Canvas to above frame-2-------------------------------
        # create horizontal layout
        self.HorizontalLayout_middle = QtWidgets.QHBoxLayout(self.graphframe)
        self.HorizontalLayout_middle.setObjectName("HorizontalLayout_3")

        # #Canvas Add here
        # self.figure, self.ax = plt.subplots(constrained_layout=True)
        # self.canvas=FigureCanvas(self.figure)
        # #end of canvas

        # Canvas Add here
        self.figure = Figure()
        self.ax = self.figure.subplots()
        self.canvas = FigureCanvas(self.figure)
        # end of canvas

        # add canvas to layout
        self.HorizontalLayout_middle.addWidget(self.canvas, QtCore.Qt.AlignCenter)
        # self.HorizontalLayout_3.addWidget(self.canvas, QtCore.Qt.AlignCenter)
        # end canvas

        # plot styles
        self.ax.set_aspect('equal')
        self.ax.xaxis.set_major_locator(MultipleLocator(20))
        self.ax.yaxis.set_major_locator(MultipleLocator(20))

        # Change minor ticks to show every 5. (20/4 = 5)
        self.ax.xaxis.set_minor_locator(AutoMinorLocator(4))
        self.ax.yaxis.set_minor_locator(AutoMinorLocator(4))
        # get empty plots
        self.scat_bt = self.ax.scatter(0, 0, c="blue")
        self.plot_structure = self.ax.plot(0, 0)
        self.plot_device = self.ax.plot(0, 0)
        # Turn grid on for both major and minor ticks and style minor slightly
        # differently.
        self.ax.grid(which='major', color='#CCCCCC', linestyle='--')
        self.ax.grid(which='minor', color='#CCCCCC', linestyle=':')
        # plt.ylim(-90, 90)
        # plt.xlim(-90, 90)
        self.ax.set_xlim(-90, 90)
        self.ax.set_ylim(-90, 90)
        #plt.ion()

        self.ax.axhline(y=0, color='k')
        self.ax.axvline(x=0, color='k')
        # endplot styles

        # ------------------------------copy upto here to add Canvas to above frame-2-------------------------------

        self.verticalLayout_2.addWidget(self.graphframe)
        self.ButtonFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonFrame.setMaximumSize(QtCore.QSize(16777215, 300))

        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ButtonFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbXYZ = QtWidgets.QGroupBox(self.ButtonFrame)
        self.gbXYZ.setMinimumSize(QtCore.QSize(0, 0))
        self.gbXYZ.setObjectName("gbXYZ")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbXYZ)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.gbXYZ)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.xlabel = QtWidgets.QLabel(self.frame)
        self.xlabel.setObjectName("xlabel")
        self.horizontalLayout_8.addWidget(self.xlabel)
        self.vxLCC = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxLCC.sizePolicy().hasHeightForWidth())
        self.vxLCC.setSizePolicy(sizePolicy)
        self.vxLCC.setMinimumSize(QtCore.QSize(0, 0))
        self.vxLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxLCC.setObjectName("vxLCC")
        self.horizontalLayout_8.addWidget(self.vxLCC)
        self.vyLCC = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyLCC.sizePolicy().hasHeightForWidth())
        self.vyLCC.setSizePolicy(sizePolicy)
        self.vyLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyLCC.setObjectName("vyLCC")
        self.horizontalLayout_8.addWidget(self.vyLCC)
        self.vzLCC = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzLCC.sizePolicy().hasHeightForWidth())
        self.vzLCC.setSizePolicy(sizePolicy)
        self.vzLCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzLCC.setObjectName("vzLCC")
        self.horizontalLayout_8.addWidget(self.vzLCC)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.gbXYZ)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")



        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ylabel = QtWidgets.QLabel(self.frame_2)
        self.ylabel.setMinimumSize(QtCore.QSize(0, 50))
        self.ylabel.setObjectName("ylabel")
        self.horizontalLayout_9.addWidget(self.ylabel)
        self.vxRCC = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxRCC.sizePolicy().hasHeightForWidth())
        self.vxRCC.setSizePolicy(sizePolicy)
        self.vxRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxRCC.setObjectName("vxRCC")
        self.horizontalLayout_9.addWidget(self.vxRCC)
        self.vyRCC = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyRCC.sizePolicy().hasHeightForWidth())
        self.vyRCC.setSizePolicy(sizePolicy)
        self.vyRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyRCC.setObjectName("vyRCC")
        self.horizontalLayout_9.addWidget(self.vyRCC)
        self.vzRCC = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzRCC.sizePolicy().hasHeightForWidth())
        self.vzRCC.setSizePolicy(sizePolicy)
        self.vzRCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzRCC.setObjectName("vzRCC")
        self.horizontalLayout_9.addWidget(self.vzRCC)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.gbXYZ)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.zlabel = QtWidgets.QLabel(self.frame_4)
        self.zlabel.setMinimumSize(QtCore.QSize(0, 50))
        self.zlabel.setObjectName("zlabel")
        self.horizontalLayout_10.addWidget(self.zlabel)
        self.vxNCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vxNCC.sizePolicy().hasHeightForWidth())
        self.vxNCC.setSizePolicy(sizePolicy)
        self.vxNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vxNCC.setObjectName("vxNCC")
        self.horizontalLayout_10.addWidget(self.vxNCC)
        self.vyNCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vyNCC.sizePolicy().hasHeightForWidth())
        self.vyNCC.setSizePolicy(sizePolicy)
        self.vyNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vyNCC.setObjectName("vyNCC")
        self.horizontalLayout_10.addWidget(self.vyNCC)
        self.vzNCC = QtWidgets.QTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vzNCC.sizePolicy().hasHeightForWidth())
        self.vzNCC.setSizePolicy(sizePolicy)
        self.vzNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vzNCC.setObjectName("vzNCC")
        self.horizontalLayout_10.addWidget(self.vzNCC)
        self.verticalLayout.addWidget(self.frame_4)
        self.fbtnXYZ = QtWidgets.QFrame(self.gbXYZ)
        self.fbtnXYZ.setMinimumSize(QtCore.QSize(0, 50))
        
        self.fbtnXYZ.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fbtnXYZ.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fbtnXYZ.setObjectName("fbtnXYZ")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fbtnXYZ)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnXYZ = QtWidgets.QPushButton(self.fbtnXYZ)
        self.btnXYZ.clicked.connect(self.Get_Scurve_XYZ)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXYZ.sizePolicy().hasHeightForWidth())
        self.btnXYZ.setSizePolicy(sizePolicy)
        self.btnXYZ.setIcon(icon)
        self.btnXYZ.setObjectName("btnXYZ")
        self.horizontalLayout_3.addWidget(self.btnXYZ)
        self.btnHelpXYZ = QtWidgets.QPushButton(self.fbtnXYZ)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHelpXYZ.sizePolicy().hasHeightForWidth())
        self.btnHelpXYZ.setSizePolicy(sizePolicy)
        self.btnHelpXYZ.setObjectName("btnHelpXYZ")
        self.horizontalLayout_3.addWidget(self.btnHelpXYZ)
        self.verticalLayout.addWidget(self.fbtnXYZ)
        self.horizontalLayout_2.addWidget(self.gbXYZ)
        self.gbEnface = QtWidgets.QGroupBox(self.ButtonFrame)
        self.gbEnface.setMinimumSize(QtCore.QSize(0, 0))
        self.gbEnface.setObjectName("gbEnface")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbEnface)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.elabel1 = QtWidgets.QLabel(self.gbEnface)
        self.elabel1.setObjectName("elabel1")
        self.verticalLayout_3.addWidget(self.elabel1)
        self.vRLEnface = QtWidgets.QTextEdit(self.gbEnface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vRLEnface.sizePolicy().hasHeightForWidth())
        self.vRLEnface.setSizePolicy(sizePolicy)
        self.vRLEnface.setObjectName("vRLEnface")
        self.verticalLayout_3.addWidget(self.vRLEnface)
        self.elabel2 = QtWidgets.QLabel(self.gbEnface)
        self.elabel2.setObjectName("elabel2")
        self.verticalLayout_3.addWidget(self.elabel2)
        self.vCCEnface = QtWidgets.QTextEdit(self.gbEnface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vCCEnface.sizePolicy().hasHeightForWidth())
        self.vCCEnface.setSizePolicy(sizePolicy)
        self.vCCEnface.setObjectName("vCCEnface")
        self.verticalLayout_3.addWidget(self.vCCEnface)
        self.fbtnEnface = QtWidgets.QFrame(self.gbEnface)
        self.fbtnEnface.setMinimumSize(QtCore.QSize(0, 0))
        self.fbtnEnface.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fbtnEnface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fbtnEnface.setObjectName("fbtnEnface")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fbtnEnface)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btncEnface = QtWidgets.QPushButton(self.fbtnEnface)
        self.btncEnface.clicked.connect(self.Get_Scurve_enface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncEnface.sizePolicy().hasHeightForWidth())
        self.btncEnface.setSizePolicy(sizePolicy)
        self.btncEnface.setIcon(icon)
        self.btncEnface.setObjectName("btncEnface")
        self.horizontalLayout_4.addWidget(self.btncEnface)
        self.btnEnfaceHelp = QtWidgets.QPushButton(self.fbtnEnface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnfaceHelp.sizePolicy().hasHeightForWidth())
        self.btnEnfaceHelp.setSizePolicy(sizePolicy)
        self.btnEnfaceHelp.setObjectName("btnEnfaceHelp")
        self.horizontalLayout_4.addWidget(self.btnEnfaceHelp)
        self.verticalLayout_3.addWidget(self.fbtnEnface)
        self.horizontalLayout_2.addWidget(self.gbEnface)
        self.groupBox = QtWidgets.QGroupBox(self.ButtonFrame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plane1frame = QtWidgets.QFrame(self.groupBox)
        self.plane1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plane1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plane1frame.setObjectName("plane1frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.plane1frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.p1label = QtWidgets.QLabel(self.plane1frame)
        self.p1label.setObjectName("p1label")
        self.horizontalLayout_5.addWidget(self.p1label)
        self.vRLP1 = QtWidgets.QTextEdit(self.plane1frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vRLP1.sizePolicy().hasHeightForWidth())
        self.vRLP1.setSizePolicy(sizePolicy)
        self.vRLP1.setStatusTip("")
        self.vRLP1.setWhatsThis("")
        self.vRLP1.setObjectName("vRLP1")
        self.horizontalLayout_5.addWidget(self.vRLP1)
        self.vCCP1 = QtWidgets.QTextEdit(self.plane1frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vCCP1.sizePolicy().hasHeightForWidth())
        self.vCCP1.setSizePolicy(sizePolicy)
        self.vCCP1.setObjectName("vCCP1")
        self.horizontalLayout_5.addWidget(self.vCCP1)
        self.verticalLayout_4.addWidget(self.plane1frame)
        self.plane2frame = QtWidgets.QFrame(self.groupBox)
        self.plane2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plane2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plane2frame.setObjectName("plane2frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.plane2frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.p2label = QtWidgets.QLabel(self.plane2frame)
        self.p2label.setObjectName("p2label")
        self.horizontalLayout_6.addWidget(self.p2label)
        self.vRLP2 = QtWidgets.QTextEdit(self.plane2frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vRLP2.sizePolicy().hasHeightForWidth())
        self.vRLP2.setSizePolicy(sizePolicy)
        self.vRLP2.setObjectName("vRLP2")
        self.horizontalLayout_6.addWidget(self.vRLP2)
        self.vCCP2 = QtWidgets.QTextEdit(self.plane2frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vCCP2.sizePolicy().hasHeightForWidth())
        self.vCCP2.setSizePolicy(sizePolicy)
        self.vCCP2.setObjectName("vCCP2")
        self.horizontalLayout_6.addWidget(self.vCCP2)
        self.verticalLayout_4.addWidget(self.plane2frame)
        self.frameplanebutton = QtWidgets.QFrame(self.groupBox)
        self.frameplanebutton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameplanebutton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameplanebutton.setObjectName("frameplanebutton")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameplanebutton)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnPcal = QtWidgets.QPushButton(self.frameplanebutton)
        self.btnPcal.setIcon(icon)
        self.btnPcal.setObjectName("btnPcal")
        self.btnPcal.clicked.connect(self.Get_SCruve_Plane)
        self.horizontalLayout_7.addWidget(self.btnPcal)
        self.btnPHelp = QtWidgets.QPushButton(self.frameplanebutton)
        self.btnPHelp.setObjectName("btnPHelp")
        self.horizontalLayout_7.addWidget(self.btnPHelp)
        self.verticalLayout_4.addWidget(self.frameplanebutton)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.ButtonFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1329, 26))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.clicked.connect(self.goBack)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBack.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon2)
        self.btnBack.setIconSize(QtCore.QSize(40, 40))
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout_2.addWidget(self.btnBack)
        self.btnBack.setText("Go Back")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "S-Curve MDCT - NAVICath"))
        self.gbXYZ.setTitle(_translate("MainWindow", "Cusp Coordinates Values"))
        self.xlabel.setText(_translate("MainWindow", "LCC Coordinates"))
        self.vxLCC.setPlaceholderText(_translate("MainWindow", "X Value"))
        self.vyLCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzLCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.ylabel.setText(_translate("MainWindow", "RCC Coordinates"))
        self.vxRCC.setPlaceholderText(_translate("MainWindow", "X Value"))
        self.vyRCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzRCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.zlabel.setText(_translate("MainWindow", "NCC Coordinates"))
        self.vxNCC.setPlaceholderText(_translate("MainWindow", "X Value"))
        self.vyNCC.setPlaceholderText(_translate("MainWindow", "Y Value"))
        self.vzNCC.setPlaceholderText(_translate("MainWindow", "Z Value"))
        self.btnXYZ.setText(_translate("MainWindow", "Calculate"))
        self.btnHelpXYZ.setText(_translate("MainWindow", "Help"))
        self.gbEnface.setTitle(_translate("MainWindow", "Enface Values"))
        self.elabel1.setText(_translate("MainWindow", "RAO or LAO Enface Value"))
        self.vRLEnface.setPlaceholderText(_translate("MainWindow", "RAO in negative, LAO in Positive"))
        self.elabel2.setText(_translate("MainWindow", "CRAN or CAUD Enface Value"))
        self.vCCEnface.setPlaceholderText(_translate("MainWindow", "CAUD in negative, CRAN in Positive"))
        self.btncEnface.setText(_translate("MainWindow", "Calculate"))
        self.btnEnfaceHelp.setText(_translate("MainWindow", "Help"))
        self.groupBox.setTitle(_translate("MainWindow", "Plane Values"))
        self.p1label.setText(_translate("MainWindow", "PLANE 1"))
        self.vRLP1.setToolTip(_translate("MainWindow", "RAO or LAO"))
        self.vRLP1.setPlaceholderText(_translate("MainWindow", "RAO in negative, LAO in Positive"))
        self.vCCP1.setPlaceholderText(_translate("MainWindow", "CAUD in negative, CRAN in Positive"))
        self.p2label.setText(_translate("MainWindow", "PLANE 2"))
        self.vRLP2.setPlaceholderText(_translate("MainWindow", "RAO in negative, LAO in Positive"))
        self.vCCP2.setPlaceholderText(_translate("MainWindow", "CAUD in negative, CRAN in Positive"))
        self.btnPcal.setText(_translate("MainWindow", "Calculate"))
        self.btnPHelp.setText(_translate("MainWindow", "Help"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))


import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
SCurveMDCT_ui = Ui_MainWindow()
SCurveMDCT_ui.setupUi(MainWindow)
# MainWindow.shindowow()

